### ISSUE TITLE
Create FreeBSD Port/Package for setuptools-pkg

### ISSUE THREAD

**Issue by koobs** [kxepal/setuptools-pkg#1]
I'm creating a FreeBSD port for setuptools-pkg, this issue is to document that. The commit landing the port will reference this issue.

Thank you for creating this package!

**Comment by kxepal** [comment]
Cool! Thank you!

**Comment by koobs** [comment]
Port committed. There are a number of minor issues related to tests/test dependencies that I will report/create PR's for separately
